### ISSUE TITLE
The `nns/root` canister's Candid service does not show up

### ISSUE THREAD

**Issue by ggreif** [ic-cubes/ic-tools#5]
Thus it is not possible to use a Candid UI for its methods.

**Comment by FloorLamp** [comment]
Added here: https://github.com/ic-cubes/ic-tools/commit/c5739f10efaed79ede7c82b429203dd1eae2a5b7#diff-c33b98523278e46ee8b08a66131d2fe4e153e7b8ace2d2104188bc91eae399e6

**Comment by ggreif** [comment]
Fixed by #6.

**Comment by ggreif** [comment]
We are on the track.
